name: DBNet
base: ['config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 0
trainer:
  seed: 2
  epochs: 100
  log_iter: 10
  show_images_iter: 100
  resume_checkpoint: 'output\DBNet_resnet18_FPN_DBHead\checkpoint\model_latest.pth'  # 'output\DBNet_resnet18_FPN_DBHead\checkpoint\model_best.pth'
  finetune_checkpoint: ''  # 'output\DBNet_resnet18_FPN_DBHead\checkpoint\model_latest.pth'
  output_dir: output
  tensorboard: false
dataset:
  train:
    dataset:
      args:
        data_path:
          - ./datasets/train.txt
        img_mode: RGB
    loader:
      batch_size: 32
      shuffle: true
      pin_memory: true
      num_workers: 4
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - ./datasets/test.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 826
              resize_text_polys: False
        img_mode: RGB
    loader:
      batch_size: 16
      shuffle: true
      pin_memory: false
      num_workers: 8
      collate_fn: 'ICDARCollectFN' # ICDARCollectFN
